# Generated by Django 4.1.5 on 2023-02-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
